// Auto-generated by generate-list.js. Do not edit by hand —
// re-run the script instead after changing the images/ folder.
//
// This placeholder is empty until you add images and run:
//   node generate-list.js
const CHARACTERS = [];
