// Run this locally whenever you add/remove images:
//   node generate-list.js
//
// It scans the /images folder and writes characters.js, deriving each
// character's display name from its filename.
//
// Naming convention for images: lowercase, words separated by underscores,
// e.g. hu_tao.webp -> "Hu Tao", raiden_shogun.webp -> "Raiden Shogun".
//
// If a filename can't be auto-converted correctly (accents, apostrophes,
// etc.), add a manual override in the OVERRIDES map below instead of
// renaming the file.

const fs = require("fs");
const path = require("path");

const IMAGES_DIR = path.join(__dirname, "images");
const OUTPUT_FILE = path.join(__dirname, "characters.js");
const VALID_EXTENSIONS = [".webp", ".png", ".jpg", ".jpeg"];

// filename (without extension) -> display name, for the rare exception
// the automatic title-casing doesn't handle correctly.
const OVERRIDES = {
  // "childe": "Childe (Tartaglia)",
};

function toDisplayName(basename) {
  if (OVERRIDES[basename]) return OVERRIDES[basename];
  return basename
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function main() {
  if (!fs.existsSync(IMAGES_DIR)) {
    console.error(`No images/ folder found at ${IMAGES_DIR}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(IMAGES_DIR)
    .filter((f) => VALID_EXTENSIONS.includes(path.extname(f).toLowerCase()))
    .sort();

  if (files.length === 0) {
    console.error("No image files found in images/. Add some and re-run.");
    process.exit(1);
  }

  const characters = files.map((file) => {
    const basename = path.basename(file, path.extname(file));
    return { name: toDisplayName(basename), file: `images/${file}` };
  });

  const output =
    "// Auto-generated by generate-list.js. Do not edit by hand —\n" +
    "// re-run the script instead after changing the images/ folder.\n" +
    "const CHARACTERS = " +
    JSON.stringify(characters, null, 2) +
    ";\n";

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Wrote ${characters.length} characters to ${OUTPUT_FILE}`);
}

main();
